### ISSUE TITLE
Add Ubuntu 20 images

### ISSUE THREAD

**Issue by jgarver** [tianocore/containers#12]
Officially, the NVIDIA JetPack requires Ubuntu 20.x.  As a result, we prefer Ubuntu 20.x when building, running CI, and when supporting customers.  We'd like to add Ubuntu 20.x build and dev images to this repo and reference them in our developer build instructions.  I expect these to be identical in spirit to the existing fedora images, just based on Ubuntu.

I'll open a PR that introduces these images.

**Comment by osteffenrh** [comment]
We have Ubuntu 20 images now, see
- #13
