### ISSUE TITLE
Donating a container image used for unofficial EDK2 nightly builds

### ISSUE THREAD

**Issue by retrage** [tianocore/containers#3]
I've been running [unofficial edk2 nightly builds](https://github.com/retrage/edk2-nightly), which provide UEFI firmware images for virtual machines and UEFI shell binaries. The builds run on the container image [served on GitHub Packages](https://github.com/retrage/edk2-nightly/pkgs/container/edk2-nightly) to focus on the reproducibility. The image is created from [the Dockerfile](https://github.com/retrage/edk2-nightly/blob/master/Dockerfile).

I think it's worth donating the container image to this official repository. I know the image still lacks some dependencies to build with official Python CI tools, but the container image is time-tested, so I'm happy to create a PR and improve the image.

The EDK2 CI already has working Azure Pipelines configs based on the Azure provided VM images. If no one cares about reproducibility, there is no need for PR.

**Comment by osteffenrh** [comment]
Thank you, @retrage.
We now have something very similar to what you proposed.

I see that you are building nasm from sources. That could maybe become necessary here too, depending how quickly EDK2 and Fedora move up with the nasm versions. Let's keep that snippet for future reference.

I would close this for now. Thanks again!
