### ISSUE TITLE
Images should be public

### ISSUE THREAD

**Issue by osteffenrh** [tianocore/containers#4]
Currently, the docker images we generate are marked as private.
They are listed under "Packages" in this repo.

![Screenshot from 2022-05-31 09-04-00](https://user-images.githubusercontent.com/95756456/171112917-dd2c7c56-1368-4e8c-a17c-7246216256f8.png)

They can be set to public, but that requires more rights than I have on this repo.
After clicking on one of them (main repo view), then there should be "Package settings" in the right column, below "Contributors".

@miki-intel-work, can you have a look? Not sure who is an admin on this repo.

**Comment by cfernald** [comment]
@spbrogan , do you have permissions for this?

**Comment by miki-intel-work** [comment]
I do not have the necessary permissions. @cfernald

**Comment by cfernald** [comment]
Mike Kinney allowed public packages and Sean set the existing packages to public. Closing this issue.
