### ISSUE TITLE
Fedora 35: Add Powershell support

### ISSUE THREAD

**Issue by makubacki** [tianocore/containers#51]
**Is your feature request related to a problem? Please describe.**
Yes. Many pipeline scripts are written for Powershell. Powershell was previously supported in Azure hosted Linux VM images and Azure Pipelines provides a cross-platform Powershell task. Powershell is not currently installed in the Fedora 35 container image.

**Describe the solution you'd like**
Install Powershell in the Fedora 35 container image.

**Describe alternatives you've considered**
Converting scripts from Powershell to alternatives. That's considered too costly considering this container image is the only blocker to maintaining compatibility.

**Additional context**

**Comment by osteffenrh** [comment]
done in https://github.com/tianocore/containers/pull/52
