### ISSUE TITLE
Please create CI containers with gcc 12

### ISSUE THREAD

**Issue by vlsunil** [tianocore/containers#59]
**Is your feature request related to a problem? Please describe.**
RISC-V build needs to move to gcc12 by updating tools_def.template. This is an incompatible change and hence it would break CI tests with GCC < 12. So, request CI container image with GCC updated to 12 for testing. Once things are fine, we can update both CI image used and the patch together.

**Describe the solution you'd like**
CI container image with GCC 12

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by osteffenrh** [comment]
Closed by #60
